build:
  environment:
    php:
      pecl_extensions:
        - zip
    variables:
      APP_NAME: cms_pico
      NEXTCLOUD: releases/latest
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
          pecl_extensions:
            - xdebug-2.9.8
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - php --info
          - composer --version

          - make build version=latest
          - cp build/$APP_NAME-latest.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/build
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run --standard=.phpcs.xml
          - js-scrutinizer-run

          - cd ~/nextcloud
          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - command: php ~/phpunit.phar --configuration tests/phpunit.xml --coverage-clover ~/build/tests/clover.xml
            idle_timeout: 1200
            coverage:
              file: tests/clover.xml
              format: clover

    test-nc18-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-18
      dependencies: &dependencies
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup: &setup
        override:
          - php --info
          - composer --version

          - make build version=latest
          - cp build/$APP_NAME-latest.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests: &tests
        override:
          - cd ~/nextcloud
          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc18-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: releases/latest-18
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc18-php74:
      environment:
        php: &php74
          version: 7.4
          compile_options: '--enable-gd --with-openssl --with-curl --with-pdo-mysql --with-mysqli --with-freetype --enable-mbstring --enable-mbregex --enable-exif --enable-bcmath --with-mhash --with-xmlrpc --with-xsl --enable-opcache --enable-intl --with-pear --with-gettext --enable-fpm --with-zlib-dir --with-zlib --disable-rpath --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-sysvsem --enable-sysvshm --enable-pcntl'
        variables:
          NEXTCLOUD: releases/latest-18
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc19-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-19
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc19-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: releases/latest-19
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc19-php74:
      environment:
        php: *php74
        variables:
          NEXTCLOUD: releases/latest-19
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc20-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-20
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc20-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: releases/latest-20
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-nc20-php74:
      environment:
        php: *php74
        variables:
          NEXTCLOUD: releases/latest-20
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-master-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-master-php74:
      environment:
        php: *php74
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

    test-master-php80:
      environment:
        php:
          version: 8.0
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies: *dependencies
      project_setup: *setup
      tests: *tests

checks:
  php: true
  javascript: true

filter:
  excluded_paths:
    - appdata/plugins/
    - appdata/themes/
    - build/
    - l10n/
    - tests/
  dependency_paths:
    - vendor/
    - nextcloud/
